name: CI

on:
  push:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Create dummy Firebase service account for build
        working-directory: backend
        run: |
          mkdir -p src/config
          echo '{"project_id":"dummy","client_email":"dummy@example.com","private_key":"-----BEGIN PRIVATE KEY-----\nMIIB\n-----END PRIVATE KEY-----\n"}' > src/config/serviceAccountKey.json

      - name: Build backend
        working-directory: backend
        run: npm run build

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build
